# @package _global_
absolute_root_path: /work3/s204138/MachineUnlearning #local # if this is set to "local" we use the __file__ to infer the absolute directory. Otherwise provide and absolute path.

defaults:
  - _self_
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

# Weights & Biases logging
logging:
  logger: "wandb" # wandb, sqlite, or disabled
  project: "machine-unlearning"
  name: "experiment_4"
  group: "synthetic_data_evaluation"
  dir: "./logs/wandb"
  wandb: 
    mode: offline #"offline"

# Data generation parameters
data:
  dataset_name: "MNIST"
  subsample_size: 10000
  n_forget_points: 100
  batch_size: 16
  n_classes: 10
  n_channels: 3
  # cifar parameters
  image_size:
    - 32
    - 32
  patch_size:
    - 4
    - 4

trainer: 
  lr: 0.001
  n_epochs: 30
  disable_tqdm: False
  do_early_stopping: True
  weight_decay: 0.0
  optimizer_name: Adam
  lr_scheduler: 

sisa:
  n_shards: 10 #5
  n_slices: 10 #5
  model_type: 'neural-network' # vision-transformer
  neural_network_parameters: # constituent model parameters
    width_factor: 0.5
    n_layers: 3

amnesiac:
  gradient_checkpoint_dir: /work3/s204138/MachineUnlearning #/Users/michaelharborg/Desktop/Masters-thesis/exp4/weights

model: 
  seed: 42 #MNIST: 42
  model_type: 'neural-network'
  neural_network_parameters:
    width_factor: 4 # MNIST: 4
    n_layers: 3 # MNIST: 3
  vision_transformer_parameters:
    d_hidden: 512
    d_ff: 2048
    d_k: 64
    n_layers: 6
    n_heads: 6
    tau: 64 # sqrt(tau) is used for scaling in self attention
    dropout_prob: 0.0
    pooling_type: max

unlearn:
  method: "retrain"

