# @package _global_

defaults:
  - _self_
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

# Weights & Biases logging
logging:
  logger: "wandb" # wandb, sqlite, or disabled
  project: "machine-unlearning"
  name: "experiment_1"
  group: "synthetic_data_evaluation"
  dir: "./logs/wandb"
  wandb: 
    mode: "offline"


# Data generation parameters
data:
  dataset: "data/data_1.npz" # reference the data file
  batch_size: 8
  n_classes: 3

trainer: 
  lr: 0.001
  n_epochs: 30
  disable_tqdm: False
  do_early_stopping: True
  weight_decay: 0.0 # MNIST: 0.0
  optimizer_name: Adam
  lr_scheduler: 

sisa:
  n_shards: 3
  n_slices: 3

model: 
  seed: 42
  device: "cpu"

unlearn:
  method: "retrain"

compress_pdfs: false