# @package _global_

defaults:
  - _self_
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

# Weights & Biases logging
logging:
  logger: "wandb" # wandb, sqlite, or disabled
  project: "machine-unlearning"
  name: "experiment_1"
  group: "synthetic_data_evaluation"
  dir: "./logs/wandb"
  wandb: 
    mode: "offline"


# Data generation parameters
data:
  dataset: "data/data_1.npz" # reference the data file
  batch_size: 16
  n_classes: 3

trainer: 
  lr: 0.001
  n_epochs: 20
  disable_tqdm: False
  do_early_stopping: True

model: 
  seed: 42
  device: "cpu"

unlearn:
  method: "retrain"

