# @package hydra.launcher
_target_: hydra_plugins.hydra_ray_launcher.ray_launcher.RayLauncher
ray:
  init:
    address: null  # Local Ray cluster
    num_cpus: 8  # Adjust based on your machine's capabilities
    num_gpus: 0  # Set to the number of GPUs you want to use
    include_dashboard: true  # Enable the dashboard
    dashboard_host: "127.0.0.1"  # Localhost
    dashboard_port: 8265  # Default Ray dashboard port
  remote:
    max_retries: 3
    num_cpus: 1  # CPUs per task
    num_gpus: 0  # GPUs per task